server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.48.164:3306/camunda?&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&verifyServerCertificate=false&requireSSL=false
    username: root
    password: root

camunda.bpm.admin-user:
  id: camunda
  password: camunda